### ISSUE TITLE
Add Cargo.lock

### ISSUE THREAD

**Issue by michaeladler** [pitkley/i3nator#9]
Could you please add a `Cargo.lock` to this project? This would help packaging your project for [NixOS](https://nixos.org/nixpkgs/manual/#compiling-rust-applications-with-cargo).

**Comment by pitkley** [comment]
Hi @michaeladler. I'm glad there is enough interest for a package for NixOS. I'll gladly add the lock-file, sorry that it is missing in the first place!

I expect to add it within the next 1-2 days, and I'll update this issue once added.

**Comment by pitkley** [comment]
@michaeladler I have pushed the missing `Cargo.lock` file. Please feel free to reopen or reach out in another issue should there be anything else required! 👍
